/* GENERATED by tools/arduino/gen-ns0.c -- do not edit.
 *
 * A const, flash-resident namespace zero: 48 nodes, read off a real
 * MINIMAL server after run_startup rather than inferred from the nodeset.
 */

#include "ua_ns0_flash.h"

static const UA_ReferenceTarget n0_k0[] = {
  {UA_NS0_NP(0, 90u), 3450041679u},
};
static const UA_NodeReferenceKind n0_refs[] = {
  {{(UA_ReferenceTarget*)n0_k0}, 1, false, 6, true},
};
static const UA_LocalizedTextListEntry n0_dn = {NULL, {{0, NULL}, {12, (UA_Byte*)"BaseDataType"}}};
static const UA_ReferenceTarget n1_k0[] = {
  {UA_NS0_NP(0, 33u), 988982737u},
  {UA_NS0_NP(0, 32u), 2402577246u},
};
static const UA_ReferenceTarget n1_k1[] = {
  {UA_NS0_NP(0, 91u), 1985572910u},
};
static const UA_NodeReferenceKind n1_refs[] = {
  {{(UA_ReferenceTarget*)n1_k0}, 2, false, 1, false},
  {{(UA_ReferenceTarget*)n1_k1}, 1, false, 6, true},
};
static const UA_LocalizedTextListEntry n1_dn = {NULL, {{0, NULL}, {10, (UA_Byte*)"References"}}};
static const UA_ReferenceTarget n2_k0[] = {
  {UA_NS0_NP(0, 31u), 1778822472u},
};
static const UA_ReferenceTarget n2_k1[] = {
  {UA_NS0_NP(0, 37u), 3466333121u},
  {UA_NS0_NP(0, 38u), 1125380941u},
  {UA_NS0_NP(0, 39u), 724490818u},
  {UA_NS0_NP(0, 40u), 2456996359u},
  {UA_NS0_NP(0, 41u), 3500881852u},
  {UA_NS0_NP(0, 17603u), 1101584319u},
};
static const UA_NodeReferenceKind n2_refs[] = {
  {{(UA_ReferenceTarget*)n2_k0}, 1, false, 1, true},
  {{(UA_ReferenceTarget*)n2_k1}, 6, false, 1, false},
};
static const UA_LocalizedTextListEntry n2_dn = {NULL, {{0, NULL}, {25, (UA_Byte*)"NonHierarchicalReferences"}}};
static const UA_ReferenceTarget n3_k0[] = {
  {UA_NS0_NP(0, 31u), 1778822472u},
};
static const UA_ReferenceTarget n3_k1[] = {
  {UA_NS0_NP(0, 34u), 3673173410u},
  {UA_NS0_NP(0, 35u), 3594421680u},
  {UA_NS0_NP(0, 36u), 2187806971u},
};
static const UA_NodeReferenceKind n3_refs[] = {
  {{(UA_ReferenceTarget*)n3_k0}, 1, false, 1, true},
  {{(UA_ReferenceTarget*)n3_k1}, 3, false, 1, false},
};
static const UA_LocalizedTextListEntry n3_dn = {NULL, {{0, NULL}, {22, (UA_Byte*)"HierarchicalReferences"}}};
static const UA_ReferenceTarget n4_k0[] = {
  {UA_NS0_NP(0, 33u), 988982737u},
};
static const UA_ReferenceTarget n4_k1[] = {
  {UA_NS0_NP(0, 44u), 3755298068u},
  {UA_NS0_NP(0, 45u), 31892320u},
};
static const UA_NodeReferenceKind n4_refs[] = {
  {{(UA_ReferenceTarget*)n4_k0}, 1, false, 1, true},
  {{(UA_ReferenceTarget*)n4_k1}, 2, false, 1, false},
};
static const UA_LocalizedTextListEntry n4_dn = {NULL, {{0, NULL}, {8, (UA_Byte*)"HasChild"}}};
static const UA_ReferenceTarget n5_k0[] = {
  {UA_NS0_NP(0, 33u), 988982737u},
};
static const UA_NodeReferenceKind n5_refs[] = {
  {{(UA_ReferenceTarget*)n5_k0}, 1, false, 1, true},
};
static const UA_LocalizedTextListEntry n5_dn = {NULL, {{0, NULL}, {9, (UA_Byte*)"Organizes"}}};
static const UA_ReferenceTarget n6_k0[] = {
  {UA_NS0_NP(0, 33u), 988982737u},
};
static const UA_ReferenceTarget n6_k1[] = {
  {UA_NS0_NP(0, 48u), 323681280u},
};
static const UA_NodeReferenceKind n6_refs[] = {
  {{(UA_ReferenceTarget*)n6_k0}, 1, false, 1, true},
  {{(UA_ReferenceTarget*)n6_k1}, 1, false, 1, false},
};
static const UA_LocalizedTextListEntry n6_dn = {NULL, {{0, NULL}, {14, (UA_Byte*)"HasEventSource"}}};
static const UA_ReferenceTarget n7_k0[] = {
  {UA_NS0_NP(0, 32u), 2402577246u},
};
static const UA_NodeReferenceKind n7_refs[] = {
  {{(UA_ReferenceTarget*)n7_k0}, 1, false, 1, true},
};
static const UA_LocalizedTextListEntry n7_dn = {NULL, {{0, NULL}, {16, (UA_Byte*)"HasModellingRule"}}};
static const UA_ReferenceTarget n8_k0[] = {
  {UA_NS0_NP(0, 32u), 2402577246u},
};
static const UA_NodeReferenceKind n8_refs[] = {
  {{(UA_ReferenceTarget*)n8_k0}, 1, false, 1, true},
};
static const UA_LocalizedTextListEntry n8_dn = {NULL, {{0, NULL}, {11, (UA_Byte*)"HasEncoding"}}};
static const UA_ReferenceTarget n9_k0[] = {
  {UA_NS0_NP(0, 32u), 2402577246u},
};
static const UA_NodeReferenceKind n9_refs[] = {
  {{(UA_ReferenceTarget*)n9_k0}, 1, false, 1, true},
};
static const UA_LocalizedTextListEntry n9_dn = {NULL, {{0, NULL}, {14, (UA_Byte*)"HasDescription"}}};
static const UA_ReferenceTarget n10_k0[] = {
  {UA_NS0_NP(0, 32u), 2402577246u},
};
static const UA_NodeReferenceKind n10_refs[] = {
  {{(UA_ReferenceTarget*)n10_k0}, 1, false, 1, true},
};
static const UA_LocalizedTextListEntry n10_dn = {NULL, {{0, NULL}, {17, (UA_Byte*)"HasTypeDefinition"}}};
static const UA_ReferenceTarget n11_k0[] = {
  {UA_NS0_NP(0, 32u), 2402577246u},
};
static const UA_NodeReferenceKind n11_refs[] = {
  {{(UA_ReferenceTarget*)n11_k0}, 1, false, 1, true},
};
static const UA_LocalizedTextListEntry n11_dn = {NULL, {{0, NULL}, {14, (UA_Byte*)"GeneratesEvent"}}};
static const UA_ReferenceTarget n12_k0[] = {
  {UA_NS0_NP(0, 34u), 3673173410u},
};
static const UA_ReferenceTarget n12_k1[] = {
  {UA_NS0_NP(0, 46u), 511614031u},
  {UA_NS0_NP(0, 47u), 3041945443u},
};
static const UA_NodeReferenceKind n12_refs[] = {
  {{(UA_ReferenceTarget*)n12_k0}, 1, false, 1, true},
  {{(UA_ReferenceTarget*)n12_k1}, 2, false, 1, false},
};
static const UA_LocalizedTextListEntry n12_dn = {NULL, {{0, NULL}, {10, (UA_Byte*)"Aggregates"}}};
static const UA_ReferenceTarget n13_k0[] = {
  {UA_NS0_NP(0, 34u), 3673173410u},
};
static const UA_NodeReferenceKind n13_refs[] = {
  {{(UA_ReferenceTarget*)n13_k0}, 1, false, 1, true},
};
static const UA_LocalizedTextListEntry n13_dn = {NULL, {{0, NULL}, {10, (UA_Byte*)"HasSubtype"}}};
static const UA_ReferenceTarget n14_k0[] = {
  {UA_NS0_NP(0, 44u), 3755298068u},
};
static const UA_NodeReferenceKind n14_refs[] = {
  {{(UA_ReferenceTarget*)n14_k0}, 1, false, 1, true},
};
static const UA_LocalizedTextListEntry n14_dn = {NULL, {{0, NULL}, {11, (UA_Byte*)"HasProperty"}}};
static const UA_ReferenceTarget n15_k0[] = {
  {UA_NS0_NP(0, 44u), 3755298068u},
};
static const UA_ReferenceTarget n15_k1[] = {
  {UA_NS0_NP(0, 49u), 1207311114u},
};
static const UA_NodeReferenceKind n15_refs[] = {
  {{(UA_ReferenceTarget*)n15_k0}, 1, false, 1, true},
  {{(UA_ReferenceTarget*)n15_k1}, 1, false, 1, false},
};
static const UA_LocalizedTextListEntry n15_dn = {NULL, {{0, NULL}, {12, (UA_Byte*)"HasComponent"}}};
static const UA_ReferenceTarget n16_k0[] = {
  {UA_NS0_NP(0, 36u), 2187806971u},
};
static const UA_NodeReferenceKind n16_refs[] = {
  {{(UA_ReferenceTarget*)n16_k0}, 1, false, 1, true},
};
static const UA_LocalizedTextListEntry n16_dn = {NULL, {{0, NULL}, {11, (UA_Byte*)"HasNotifier"}}};
static const UA_ReferenceTarget n17_k0[] = {
  {UA_NS0_NP(0, 47u), 3041945443u},
};
static const UA_NodeReferenceKind n17_refs[] = {
  {{(UA_ReferenceTarget*)n17_k0}, 1, false, 1, true},
};
static const UA_LocalizedTextListEntry n17_dn = {NULL, {{0, NULL}, {19, (UA_Byte*)"HasOrderedComponent"}}};
static const UA_ReferenceTarget n18_k0[] = {
  {UA_NS0_NP(0, 61u), 4179968392u},
  {UA_NS0_NP(0, 2041u), 501221827u},
};
static const UA_ReferenceTarget n18_k1[] = {
  {UA_NS0_NP(0, 88u), 2827720826u},
};
static const UA_ReferenceTarget n18_k2[] = {
  {UA_NS0_NP(0, 2253u), 4012783267u},
};
static const UA_NodeReferenceKind n18_refs[] = {
  {{(UA_ReferenceTarget*)n18_k0}, 2, false, 1, false},
  {{(UA_ReferenceTarget*)n18_k1}, 1, false, 6, true},
  {{(UA_ReferenceTarget*)n18_k2}, 1, false, 11, true},
};
static const UA_LocalizedTextListEntry n18_dn = {NULL, {{0, NULL}, {14, (UA_Byte*)"BaseObjectType"}}};
static const UA_ReferenceTarget n19_k0[] = {
  {UA_NS0_NP(0, 58u), 3400731018u},
};
static const UA_ReferenceTarget n19_k1[] = {
  {UA_NS0_NP(0, 84u), 507949538u},
  {UA_NS0_NP(0, 85u), 1082171796u},
  {UA_NS0_NP(0, 86u), 2127804505u},
  {UA_NS0_NP(0, 91u), 1985572910u},
  {UA_NS0_NP(0, 90u), 3450041679u},
  {UA_NS0_NP(0, 89u), 466044445u},
  {UA_NS0_NP(0, 88u), 2827720826u},
  {UA_NS0_NP(0, 3048u), 27087903u},
  {UA_NS0_NP(0, 87u), 417776718u},
};
static const UA_NodeReferenceKind n19_refs[] = {
  {{(UA_ReferenceTarget*)n19_k0}, 1, false, 1, true},
  {{(UA_ReferenceTarget*)n19_k1}, 9, false, 11, true},
};
static const UA_LocalizedTextListEntry n19_dn = {NULL, {{0, NULL}, {10, (UA_Byte*)"FolderType"}}};
static const UA_ReferenceTarget n20_k0[] = {
  {UA_NS0_NP(0, 63u), 1229310769u},
  {UA_NS0_NP(0, 68u), 1689974095u},
};
static const UA_ReferenceTarget n20_k1[] = {
  {UA_NS0_NP(0, 89u), 466044445u},
};
static const UA_NodeReferenceKind n20_refs[] = {
  {{(UA_ReferenceTarget*)n20_k0}, 2, false, 1, false},
  {{(UA_ReferenceTarget*)n20_k1}, 1, false, 6, true},
};
static const UA_LocalizedTextListEntry n20_dn = {NULL, {{0, NULL}, {16, (UA_Byte*)"BaseVariableType"}}};
static const UA_ReferenceTarget n21_k0[] = {
  {UA_NS0_NP(0, 62u), 2215389863u},
};
static const UA_ReferenceTarget n21_k1[] = {
  {UA_NS0_NP(0, 2254u), 4104669494u},
  {UA_NS0_NP(0, 2255u), 37925822u},
  {UA_NS0_NP(0, 2256u), 2281366037u},
  {UA_NS0_NP(0, 2257u), 2598229007u},
  {UA_NS0_NP(0, 2258u), 3413587782u},
  {UA_NS0_NP(0, 2259u), 1257332913u},
  {UA_NS0_NP(0, 2260u), 694515676u},
  {UA_NS0_NP(0, 2262u), 1880724573u},
  {UA_NS0_NP(0, 2263u), 2059064316u},
  {UA_NS0_NP(0, 2261u), 3701327738u},
  {UA_NS0_NP(0, 2264u), 2336434641u},
  {UA_NS0_NP(0, 2265u), 1450298903u},
  {UA_NS0_NP(0, 2266u), 980065788u},
};
static const UA_NodeReferenceKind n21_refs[] = {
  {{(UA_ReferenceTarget*)n21_k0}, 1, false, 1, true},
  {{(UA_ReferenceTarget*)n21_k1}, 13, false, 11, true},
};
static const UA_LocalizedTextListEntry n21_dn = {NULL, {{0, NULL}, {20, (UA_Byte*)"BaseDataVariableType"}}};
static const UA_ReferenceTarget n22_k0[] = {
  {UA_NS0_NP(0, 62u), 2215389863u},
};
static const UA_NodeReferenceKind n22_refs[] = {
  {{(UA_ReferenceTarget*)n22_k0}, 1, false, 1, true},
};
static const UA_LocalizedTextListEntry n22_dn = {NULL, {{0, NULL}, {12, (UA_Byte*)"PropertyType"}}};
static const UA_ReferenceTarget n23_k0[] = {
  {UA_NS0_NP(0, 61u), 4179968392u},
};
static const UA_ReferenceTarget n23_k1[] = {
  {UA_NS0_NP(0, 85u), 1082171796u},
  {UA_NS0_NP(0, 86u), 2127804505u},
  {UA_NS0_NP(0, 87u), 417776718u},
};
static const UA_NodeReferenceKind n23_refs[] = {
  {{(UA_ReferenceTarget*)n23_k0}, 1, false, 11, false},
  {{(UA_ReferenceTarget*)n23_k1}, 3, false, 6, false},
};
static const UA_LocalizedTextListEntry n23_dn = {NULL, {{0, NULL}, {4, (UA_Byte*)"Root"}}};
static const UA_ReferenceTarget n24_k0[] = {
  {UA_NS0_NP(0, 84u), 507949538u},
};
static const UA_ReferenceTarget n24_k1[] = {
  {UA_NS0_NP(0, 61u), 4179968392u},
};
static const UA_ReferenceTarget n24_k2[] = {
  {UA_NS0_NP(0, 2253u), 4012783267u},
};
static const UA_NodeReferenceKind n24_refs[] = {
  {{(UA_ReferenceTarget*)n24_k0}, 1, false, 6, true},
  {{(UA_ReferenceTarget*)n24_k1}, 1, false, 11, false},
  {{(UA_ReferenceTarget*)n24_k2}, 1, false, 6, false},
};
static const UA_LocalizedTextListEntry n24_dn = {NULL, {{0, NULL}, {7, (UA_Byte*)"Objects"}}};
static const UA_ReferenceTarget n25_k0[] = {
  {UA_NS0_NP(0, 84u), 507949538u},
};
static const UA_ReferenceTarget n25_k1[] = {
  {UA_NS0_NP(0, 61u), 4179968392u},
};
static const UA_ReferenceTarget n25_k2[] = {
  {UA_NS0_NP(0, 91u), 1985572910u},
  {UA_NS0_NP(0, 90u), 3450041679u},
  {UA_NS0_NP(0, 89u), 466044445u},
  {UA_NS0_NP(0, 88u), 2827720826u},
  {UA_NS0_NP(0, 3048u), 27087903u},
};
static const UA_NodeReferenceKind n25_refs[] = {
  {{(UA_ReferenceTarget*)n25_k0}, 1, false, 6, true},
  {{(UA_ReferenceTarget*)n25_k1}, 1, false, 11, false},
  {{(UA_ReferenceTarget*)n25_k2}, 5, false, 6, false},
};
static const UA_LocalizedTextListEntry n25_dn = {NULL, {{0, NULL}, {5, (UA_Byte*)"Types"}}};
static const UA_ReferenceTarget n26_k0[] = {
  {UA_NS0_NP(0, 84u), 507949538u},
};
static const UA_ReferenceTarget n26_k1[] = {
  {UA_NS0_NP(0, 61u), 4179968392u},
};
static const UA_NodeReferenceKind n26_refs[] = {
  {{(UA_ReferenceTarget*)n26_k0}, 1, false, 6, true},
  {{(UA_ReferenceTarget*)n26_k1}, 1, false, 11, false},
};
static const UA_LocalizedTextListEntry n26_dn = {NULL, {{0, NULL}, {5, (UA_Byte*)"Views"}}};
static const UA_ReferenceTarget n27_k0[] = {
  {UA_NS0_NP(0, 86u), 2127804505u},
};
static const UA_ReferenceTarget n27_k1[] = {
  {UA_NS0_NP(0, 61u), 4179968392u},
};
static const UA_ReferenceTarget n27_k2[] = {
  {UA_NS0_NP(0, 58u), 3400731018u},
};
static const UA_NodeReferenceKind n27_refs[] = {
  {{(UA_ReferenceTarget*)n27_k0}, 1, false, 6, true},
  {{(UA_ReferenceTarget*)n27_k1}, 1, false, 11, false},
  {{(UA_ReferenceTarget*)n27_k2}, 1, false, 6, false},
};
static const UA_LocalizedTextListEntry n27_dn = {NULL, {{0, NULL}, {11, (UA_Byte*)"ObjectTypes"}}};
static const UA_ReferenceTarget n28_k0[] = {
  {UA_NS0_NP(0, 86u), 2127804505u},
};
static const UA_ReferenceTarget n28_k1[] = {
  {UA_NS0_NP(0, 61u), 4179968392u},
};
static const UA_ReferenceTarget n28_k2[] = {
  {UA_NS0_NP(0, 62u), 2215389863u},
};
static const UA_NodeReferenceKind n28_refs[] = {
  {{(UA_ReferenceTarget*)n28_k0}, 1, false, 6, true},
  {{(UA_ReferenceTarget*)n28_k1}, 1, false, 11, false},
  {{(UA_ReferenceTarget*)n28_k2}, 1, false, 6, false},
};
static const UA_LocalizedTextListEntry n28_dn = {NULL, {{0, NULL}, {13, (UA_Byte*)"VariableTypes"}}};
static const UA_ReferenceTarget n29_k0[] = {
  {UA_NS0_NP(0, 86u), 2127804505u},
};
static const UA_ReferenceTarget n29_k1[] = {
  {UA_NS0_NP(0, 61u), 4179968392u},
};
static const UA_ReferenceTarget n29_k2[] = {
  {UA_NS0_NP(0, 24u), 4094197749u},
};
static const UA_NodeReferenceKind n29_refs[] = {
  {{(UA_ReferenceTarget*)n29_k0}, 1, false, 6, true},
  {{(UA_ReferenceTarget*)n29_k1}, 1, false, 11, false},
  {{(UA_ReferenceTarget*)n29_k2}, 1, false, 6, false},
};
static const UA_LocalizedTextListEntry n29_dn = {NULL, {{0, NULL}, {9, (UA_Byte*)"DataTypes"}}};
static const UA_ReferenceTarget n30_k0[] = {
  {UA_NS0_NP(0, 86u), 2127804505u},
};
static const UA_ReferenceTarget n30_k1[] = {
  {UA_NS0_NP(0, 61u), 4179968392u},
};
static const UA_ReferenceTarget n30_k2[] = {
  {UA_NS0_NP(0, 31u), 1778822472u},
};
static const UA_NodeReferenceKind n30_refs[] = {
  {{(UA_ReferenceTarget*)n30_k0}, 1, false, 6, true},
  {{(UA_ReferenceTarget*)n30_k1}, 1, false, 11, false},
  {{(UA_ReferenceTarget*)n30_k2}, 1, false, 6, false},
};
static const UA_LocalizedTextListEntry n30_dn = {NULL, {{0, NULL}, {14, (UA_Byte*)"ReferenceTypes"}}};
static const UA_ReferenceTarget n31_k0[] = {
  {UA_NS0_NP(0, 58u), 3400731018u},
};
static const UA_ReferenceTarget n31_k1[] = {
  {UA_NS0_NP(0, 3048u), 27087903u},
};
static const UA_NodeReferenceKind n31_refs[] = {
  {{(UA_ReferenceTarget*)n31_k0}, 1, false, 1, true},
  {{(UA_ReferenceTarget*)n31_k1}, 1, false, 6, true},
};
static const UA_LocalizedTextListEntry n31_dn = {NULL, {{0, NULL}, {13, (UA_Byte*)"BaseEventType"}}};
static const UA_ReferenceTarget n32_k0[] = {
  {UA_NS0_NP(0, 85u), 1082171796u},
};
static const UA_ReferenceTarget n32_k1[] = {
  {UA_NS0_NP(0, 58u), 3400731018u},
};
static const UA_ReferenceTarget n32_k2[] = {
  {UA_NS0_NP(0, 2254u), 4104669494u},
  {UA_NS0_NP(0, 2255u), 37925822u},
};
static const UA_ReferenceTarget n32_k3[] = {
  {UA_NS0_NP(0, 2256u), 2281366037u},
};
static const UA_NodeReferenceKind n32_refs[] = {
  {{(UA_ReferenceTarget*)n32_k0}, 1, false, 6, true},
  {{(UA_ReferenceTarget*)n32_k1}, 1, false, 11, false},
  {{(UA_ReferenceTarget*)n32_k2}, 2, false, 13, false},
  {{(UA_ReferenceTarget*)n32_k3}, 1, false, 14, false},
};
static const UA_LocalizedTextListEntry n32_dn = {NULL, {{0, NULL}, {6, (UA_Byte*)"Server"}}};
static const UA_ReferenceTarget n33_k0[] = {
  {UA_NS0_NP(0, 2253u), 4012783267u},
};
static const UA_ReferenceTarget n33_k1[] = {
  {UA_NS0_NP(0, 63u), 1229310769u},
};
static const UA_NodeReferenceKind n33_refs[] = {
  {{(UA_ReferenceTarget*)n33_k0}, 1, false, 13, true},
  {{(UA_ReferenceTarget*)n33_k1}, 1, false, 11, false},
};
static const UA_LocalizedTextListEntry n33_dn = {NULL, {{0, NULL}, {11, (UA_Byte*)"ServerArray"}}};
static const UA_ReferenceTarget n34_k0[] = {
  {UA_NS0_NP(0, 2253u), 4012783267u},
};
static const UA_ReferenceTarget n34_k1[] = {
  {UA_NS0_NP(0, 63u), 1229310769u},
};
static const UA_NodeReferenceKind n34_refs[] = {
  {{(UA_ReferenceTarget*)n34_k0}, 1, false, 13, true},
  {{(UA_ReferenceTarget*)n34_k1}, 1, false, 11, false},
};
static const UA_LocalizedTextListEntry n34_dn = {NULL, {{0, NULL}, {14, (UA_Byte*)"NamespaceArray"}}};
static const UA_ReferenceTarget n35_k0[] = {
  {UA_NS0_NP(0, 2253u), 4012783267u},
};
static const UA_ReferenceTarget n35_k1[] = {
  {UA_NS0_NP(0, 63u), 1229310769u},
};
static const UA_ReferenceTarget n35_k2[] = {
  {UA_NS0_NP(0, 2257u), 2598229007u},
  {UA_NS0_NP(0, 2258u), 3413587782u},
  {UA_NS0_NP(0, 2259u), 1257332913u},
  {UA_NS0_NP(0, 2260u), 694515676u},
};
static const UA_NodeReferenceKind n35_refs[] = {
  {{(UA_ReferenceTarget*)n35_k0}, 1, false, 14, true},
  {{(UA_ReferenceTarget*)n35_k1}, 1, false, 11, false},
  {{(UA_ReferenceTarget*)n35_k2}, 4, false, 14, false},
};
static const UA_LocalizedTextListEntry n35_dn = {NULL, {{0, NULL}, {12, (UA_Byte*)"ServerStatus"}}};
static const UA_ReferenceTarget n36_k0[] = {
  {UA_NS0_NP(0, 2256u), 2281366037u},
};
static const UA_ReferenceTarget n36_k1[] = {
  {UA_NS0_NP(0, 63u), 1229310769u},
};
static const UA_NodeReferenceKind n36_refs[] = {
  {{(UA_ReferenceTarget*)n36_k0}, 1, false, 14, true},
  {{(UA_ReferenceTarget*)n36_k1}, 1, false, 11, false},
};
static const UA_LocalizedTextListEntry n36_dn = {NULL, {{0, NULL}, {9, (UA_Byte*)"StartTime"}}};
static const UA_ReferenceTarget n37_k0[] = {
  {UA_NS0_NP(0, 2256u), 2281366037u},
};
static const UA_ReferenceTarget n37_k1[] = {
  {UA_NS0_NP(0, 63u), 1229310769u},
};
static const UA_NodeReferenceKind n37_refs[] = {
  {{(UA_ReferenceTarget*)n37_k0}, 1, false, 14, true},
  {{(UA_ReferenceTarget*)n37_k1}, 1, false, 11, false},
};
static const UA_LocalizedTextListEntry n37_dn = {NULL, {{0, NULL}, {11, (UA_Byte*)"CurrentTime"}}};
static const UA_ReferenceTarget n38_k0[] = {
  {UA_NS0_NP(0, 2256u), 2281366037u},
};
static const UA_ReferenceTarget n38_k1[] = {
  {UA_NS0_NP(0, 63u), 1229310769u},
};
static const UA_NodeReferenceKind n38_refs[] = {
  {{(UA_ReferenceTarget*)n38_k0}, 1, false, 14, true},
  {{(UA_ReferenceTarget*)n38_k1}, 1, false, 11, false},
};
static const UA_LocalizedTextListEntry n38_dn = {NULL, {{0, NULL}, {5, (UA_Byte*)"State"}}};
static const UA_ReferenceTarget n39_k0[] = {
  {UA_NS0_NP(0, 2256u), 2281366037u},
};
static const UA_ReferenceTarget n39_k1[] = {
  {UA_NS0_NP(0, 63u), 1229310769u},
};
static const UA_ReferenceTarget n39_k2[] = {
  {UA_NS0_NP(0, 2262u), 1880724573u},
  {UA_NS0_NP(0, 2263u), 2059064316u},
  {UA_NS0_NP(0, 2261u), 3701327738u},
  {UA_NS0_NP(0, 2264u), 2336434641u},
  {UA_NS0_NP(0, 2265u), 1450298903u},
  {UA_NS0_NP(0, 2266u), 980065788u},
};
static const UA_NodeReferenceKind n39_refs[] = {
  {{(UA_ReferenceTarget*)n39_k0}, 1, false, 14, true},
  {{(UA_ReferenceTarget*)n39_k1}, 1, false, 11, false},
  {{(UA_ReferenceTarget*)n39_k2}, 6, false, 14, false},
};
static const UA_LocalizedTextListEntry n39_dn = {NULL, {{0, NULL}, {9, (UA_Byte*)"BuildInfo"}}};
static const UA_ReferenceTarget n40_k0[] = {
  {UA_NS0_NP(0, 2260u), 694515676u},
};
static const UA_ReferenceTarget n40_k1[] = {
  {UA_NS0_NP(0, 63u), 1229310769u},
};
static const UA_NodeReferenceKind n40_refs[] = {
  {{(UA_ReferenceTarget*)n40_k0}, 1, false, 14, true},
  {{(UA_ReferenceTarget*)n40_k1}, 1, false, 11, false},
};
static const UA_LocalizedTextListEntry n40_dn = {NULL, {{0, NULL}, {11, (UA_Byte*)"ProductName"}}};
static const UA_ReferenceTarget n41_k0[] = {
  {UA_NS0_NP(0, 2260u), 694515676u},
};
static const UA_ReferenceTarget n41_k1[] = {
  {UA_NS0_NP(0, 63u), 1229310769u},
};
static const UA_NodeReferenceKind n41_refs[] = {
  {{(UA_ReferenceTarget*)n41_k0}, 1, false, 14, true},
  {{(UA_ReferenceTarget*)n41_k1}, 1, false, 11, false},
};
static const UA_LocalizedTextListEntry n41_dn = {NULL, {{0, NULL}, {10, (UA_Byte*)"ProductUri"}}};
static const UA_ReferenceTarget n42_k0[] = {
  {UA_NS0_NP(0, 2260u), 694515676u},
};
static const UA_ReferenceTarget n42_k1[] = {
  {UA_NS0_NP(0, 63u), 1229310769u},
};
static const UA_NodeReferenceKind n42_refs[] = {
  {{(UA_ReferenceTarget*)n42_k0}, 1, false, 14, true},
  {{(UA_ReferenceTarget*)n42_k1}, 1, false, 11, false},
};
static const UA_LocalizedTextListEntry n42_dn = {NULL, {{0, NULL}, {16, (UA_Byte*)"ManufacturerName"}}};
static const UA_ReferenceTarget n43_k0[] = {
  {UA_NS0_NP(0, 2260u), 694515676u},
};
static const UA_ReferenceTarget n43_k1[] = {
  {UA_NS0_NP(0, 63u), 1229310769u},
};
static const UA_NodeReferenceKind n43_refs[] = {
  {{(UA_ReferenceTarget*)n43_k0}, 1, false, 14, true},
  {{(UA_ReferenceTarget*)n43_k1}, 1, false, 11, false},
};
static const UA_LocalizedTextListEntry n43_dn = {NULL, {{0, NULL}, {15, (UA_Byte*)"SoftwareVersion"}}};
static const UA_ReferenceTarget n44_k0[] = {
  {UA_NS0_NP(0, 2260u), 694515676u},
};
static const UA_ReferenceTarget n44_k1[] = {
  {UA_NS0_NP(0, 63u), 1229310769u},
};
static const UA_NodeReferenceKind n44_refs[] = {
  {{(UA_ReferenceTarget*)n44_k0}, 1, false, 14, true},
  {{(UA_ReferenceTarget*)n44_k1}, 1, false, 11, false},
};
static const UA_LocalizedTextListEntry n44_dn = {NULL, {{0, NULL}, {11, (UA_Byte*)"BuildNumber"}}};
static const UA_ReferenceTarget n45_k0[] = {
  {UA_NS0_NP(0, 2260u), 694515676u},
};
static const UA_ReferenceTarget n45_k1[] = {
  {UA_NS0_NP(0, 63u), 1229310769u},
};
static const UA_NodeReferenceKind n45_refs[] = {
  {{(UA_ReferenceTarget*)n45_k0}, 1, false, 14, true},
  {{(UA_ReferenceTarget*)n45_k1}, 1, false, 11, false},
};
static const UA_LocalizedTextListEntry n45_dn = {NULL, {{0, NULL}, {9, (UA_Byte*)"BuildDate"}}};
static const UA_ReferenceTarget n46_k0[] = {
  {UA_NS0_NP(0, 86u), 2127804505u},
};
static const UA_ReferenceTarget n46_k1[] = {
  {UA_NS0_NP(0, 61u), 4179968392u},
};
static const UA_ReferenceTarget n46_k2[] = {
  {UA_NS0_NP(0, 2041u), 501221827u},
};
static const UA_NodeReferenceKind n46_refs[] = {
  {{(UA_ReferenceTarget*)n46_k0}, 1, false, 6, true},
  {{(UA_ReferenceTarget*)n46_k1}, 1, false, 11, false},
  {{(UA_ReferenceTarget*)n46_k2}, 1, false, 6, false},
};
static const UA_LocalizedTextListEntry n46_dn = {NULL, {{0, NULL}, {10, (UA_Byte*)"EventTypes"}}};
static const UA_ReferenceTarget n47_k0[] = {
  {UA_NS0_NP(0, 32u), 2402577246u},
};
static const UA_NodeReferenceKind n47_refs[] = {
  {{(UA_ReferenceTarget*)n47_k0}, 1, false, 1, true},
};
static const UA_LocalizedTextListEntry n47_dn = {NULL, {{0, NULL}, {12, (UA_Byte*)"HasInterface"}}};

const UA_Node ua_ns0_nodes[48] = {
  { .dataTypeNode = {
    .head = {
      .nodeId = {0, UA_NODEIDTYPE_NUMERIC, {.numeric = 24u}},
      .nodeClass = (UA_NodeClass)64,
      .browseName = {0, {12, (UA_Byte*)"BaseDataType"}},
      .displayName = (UA_LocalizedTextListEntry*)&n0_dn,
      .description = NULL,
      .writeMask = 0u,
      .referencesSize = 1,
      .references = (UA_NodeReferenceKind*)n0_refs,
      .context = NULL,
      .constructed = true
    },
    .isAbstract = true
  } },
  { .referenceTypeNode = {
    .head = {
      .nodeId = {0, UA_NODEIDTYPE_NUMERIC, {.numeric = 31u}},
      .nodeClass = (UA_NodeClass)32,
      .browseName = {0, {10, (UA_Byte*)"References"}},
      .displayName = (UA_LocalizedTextListEntry*)&n1_dn,
      .description = NULL,
      .writeMask = 0u,
      .referencesSize = 2,
      .references = (UA_NodeReferenceKind*)n1_refs,
      .context = NULL,
      .constructed = true
    },
    .isAbstract = true,
    .symmetric = true,
    .inverseName = {{0, NULL}, {10, (UA_Byte*)"References"}},
    .referenceTypeIndex = 0u,
    .subTypes = {{262143u,0u,0u,0u,}}
  } },
  { .referenceTypeNode = {
    .head = {
      .nodeId = {0, UA_NODEIDTYPE_NUMERIC, {.numeric = 32u}},
      .nodeClass = (UA_NodeClass)32,
      .browseName = {0, {25, (UA_Byte*)"NonHierarchicalReferences"}},
      .displayName = (UA_LocalizedTextListEntry*)&n2_dn,
      .description = NULL,
      .writeMask = 0u,
      .referencesSize = 2,
      .references = (UA_NodeReferenceKind*)n2_refs,
      .context = NULL,
      .constructed = true
    },
    .isAbstract = true,
    .symmetric = true,
    .inverseName = {{0, NULL}, {0, NULL}},
    .referenceTypeIndex = 4u,
    .subTypes = {{139024u,0u,0u,0u,}}
  } },
  { .referenceTypeNode = {
    .head = {
      .nodeId = {0, UA_NODEIDTYPE_NUMERIC, {.numeric = 33u}},
      .nodeClass = (UA_NodeClass)32,
      .browseName = {0, {22, (UA_Byte*)"HierarchicalReferences"}},
      .displayName = (UA_LocalizedTextListEntry*)&n3_dn,
      .description = NULL,
      .writeMask = 0u,
      .referencesSize = 2,
      .references = (UA_NodeReferenceKind*)n3_refs,
      .context = NULL,
      .constructed = true
    },
    .isAbstract = true,
    .symmetric = false,
    .inverseName = {{0, NULL}, {0, NULL}},
    .referenceTypeIndex = 3u,
    .subTypes = {{123118u,0u,0u,0u,}}
  } },
  { .referenceTypeNode = {
    .head = {
      .nodeId = {0, UA_NODEIDTYPE_NUMERIC, {.numeric = 34u}},
      .nodeClass = (UA_NodeClass)32,
      .browseName = {0, {8, (UA_Byte*)"HasChild"}},
      .displayName = (UA_LocalizedTextListEntry*)&n4_dn,
      .description = NULL,
      .writeMask = 0u,
      .referencesSize = 2,
      .references = (UA_NodeReferenceKind*)n4_refs,
      .context = NULL,
      .constructed = true
    },
    .isAbstract = true,
    .symmetric = false,
    .inverseName = {{0, NULL}, {0, NULL}},
    .referenceTypeIndex = 5u,
    .subTypes = {{90150u,0u,0u,0u,}}
  } },
  { .referenceTypeNode = {
    .head = {
      .nodeId = {0, UA_NODEIDTYPE_NUMERIC, {.numeric = 35u}},
      .nodeClass = (UA_NodeClass)32,
      .browseName = {0, {9, (UA_Byte*)"Organizes"}},
      .displayName = (UA_LocalizedTextListEntry*)&n5_dn,
      .description = NULL,
      .writeMask = 0u,
      .referencesSize = 1,
      .references = (UA_NodeReferenceKind*)n5_refs,
      .context = NULL,
      .constructed = true
    },
    .isAbstract = false,
    .symmetric = false,
    .inverseName = {{0, NULL}, {11, (UA_Byte*)"OrganizedBy"}},
    .referenceTypeIndex = 6u,
    .subTypes = {{64u,0u,0u,0u,}}
  } },
  { .referenceTypeNode = {
    .head = {
      .nodeId = {0, UA_NODEIDTYPE_NUMERIC, {.numeric = 36u}},
      .nodeClass = (UA_NodeClass)32,
      .browseName = {0, {14, (UA_Byte*)"HasEventSource"}},
      .displayName = (UA_LocalizedTextListEntry*)&n6_dn,
      .description = NULL,
      .writeMask = 0u,
      .referencesSize = 2,
      .references = (UA_NodeReferenceKind*)n6_refs,
      .context = NULL,
      .constructed = true
    },
    .isAbstract = false,
    .symmetric = false,
    .inverseName = {{0, NULL}, {13, (UA_Byte*)"EventSourceOf"}},
    .referenceTypeIndex = 7u,
    .subTypes = {{32896u,0u,0u,0u,}}
  } },
  { .referenceTypeNode = {
    .head = {
      .nodeId = {0, UA_NODEIDTYPE_NUMERIC, {.numeric = 37u}},
      .nodeClass = (UA_NodeClass)32,
      .browseName = {0, {16, (UA_Byte*)"HasModellingRule"}},
      .displayName = (UA_LocalizedTextListEntry*)&n7_dn,
      .description = NULL,
      .writeMask = 0u,
      .referencesSize = 1,
      .references = (UA_NodeReferenceKind*)n7_refs,
      .context = NULL,
      .constructed = true
    },
    .isAbstract = false,
    .symmetric = false,
    .inverseName = {{0, NULL}, {15, (UA_Byte*)"ModellingRuleOf"}},
    .referenceTypeIndex = 8u,
    .subTypes = {{256u,0u,0u,0u,}}
  } },
  { .referenceTypeNode = {
    .head = {
      .nodeId = {0, UA_NODEIDTYPE_NUMERIC, {.numeric = 38u}},
      .nodeClass = (UA_NodeClass)32,
      .browseName = {0, {11, (UA_Byte*)"HasEncoding"}},
      .displayName = (UA_LocalizedTextListEntry*)&n8_dn,
      .description = NULL,
      .writeMask = 0u,
      .referencesSize = 1,
      .references = (UA_NodeReferenceKind*)n8_refs,
      .context = NULL,
      .constructed = true
    },
    .isAbstract = false,
    .symmetric = false,
    .inverseName = {{0, NULL}, {10, (UA_Byte*)"EncodingOf"}},
    .referenceTypeIndex = 9u,
    .subTypes = {{512u,0u,0u,0u,}}
  } },
  { .referenceTypeNode = {
    .head = {
      .nodeId = {0, UA_NODEIDTYPE_NUMERIC, {.numeric = 39u}},
      .nodeClass = (UA_NodeClass)32,
      .browseName = {0, {14, (UA_Byte*)"HasDescription"}},
      .displayName = (UA_LocalizedTextListEntry*)&n9_dn,
      .description = NULL,
      .writeMask = 0u,
      .referencesSize = 1,
      .references = (UA_NodeReferenceKind*)n9_refs,
      .context = NULL,
      .constructed = true
    },
    .isAbstract = false,
    .symmetric = false,
    .inverseName = {{0, NULL}, {13, (UA_Byte*)"DescriptionOf"}},
    .referenceTypeIndex = 10u,
    .subTypes = {{1024u,0u,0u,0u,}}
  } },
  { .referenceTypeNode = {
    .head = {
      .nodeId = {0, UA_NODEIDTYPE_NUMERIC, {.numeric = 40u}},
      .nodeClass = (UA_NodeClass)32,
      .browseName = {0, {17, (UA_Byte*)"HasTypeDefinition"}},
      .displayName = (UA_LocalizedTextListEntry*)&n10_dn,
      .description = NULL,
      .writeMask = 0u,
      .referencesSize = 1,
      .references = (UA_NodeReferenceKind*)n10_refs,
      .context = NULL,
      .constructed = true
    },
    .isAbstract = false,
    .symmetric = false,
    .inverseName = {{0, NULL}, {16, (UA_Byte*)"TypeDefinitionOf"}},
    .referenceTypeIndex = 11u,
    .subTypes = {{2048u,0u,0u,0u,}}
  } },
  { .referenceTypeNode = {
    .head = {
      .nodeId = {0, UA_NODEIDTYPE_NUMERIC, {.numeric = 41u}},
      .nodeClass = (UA_NodeClass)32,
      .browseName = {0, {14, (UA_Byte*)"GeneratesEvent"}},
      .displayName = (UA_LocalizedTextListEntry*)&n11_dn,
      .description = NULL,
      .writeMask = 0u,
      .referencesSize = 1,
      .references = (UA_NodeReferenceKind*)n11_refs,
      .context = NULL,
      .constructed = true
    },
    .isAbstract = false,
    .symmetric = false,
    .inverseName = {{0, NULL}, {11, (UA_Byte*)"GeneratedBy"}},
    .referenceTypeIndex = 12u,
    .subTypes = {{4096u,0u,0u,0u,}}
  } },
  { .referenceTypeNode = {
    .head = {
      .nodeId = {0, UA_NODEIDTYPE_NUMERIC, {.numeric = 44u}},
      .nodeClass = (UA_NodeClass)32,
      .browseName = {0, {10, (UA_Byte*)"Aggregates"}},
      .displayName = (UA_LocalizedTextListEntry*)&n12_dn,
      .description = NULL,
      .writeMask = 0u,
      .referencesSize = 2,
      .references = (UA_NodeReferenceKind*)n12_refs,
      .context = NULL,
      .constructed = true
    },
    .isAbstract = true,
    .symmetric = false,
    .inverseName = {{0, NULL}, {12, (UA_Byte*)"AggregatedBy"}},
    .referenceTypeIndex = 2u,
    .subTypes = {{90116u,0u,0u,0u,}}
  } },
  { .referenceTypeNode = {
    .head = {
      .nodeId = {0, UA_NODEIDTYPE_NUMERIC, {.numeric = 45u}},
      .nodeClass = (UA_NodeClass)32,
      .browseName = {0, {10, (UA_Byte*)"HasSubtype"}},
      .displayName = (UA_LocalizedTextListEntry*)&n13_dn,
      .description = NULL,
      .writeMask = 0u,
      .referencesSize = 1,
      .references = (UA_NodeReferenceKind*)n13_refs,
      .context = NULL,
      .constructed = true
    },
    .isAbstract = false,
    .symmetric = false,
    .inverseName = {{0, NULL}, {9, (UA_Byte*)"SubtypeOf"}},
    .referenceTypeIndex = 1u,
    .subTypes = {{2u,0u,0u,0u,}}
  } },
  { .referenceTypeNode = {
    .head = {
      .nodeId = {0, UA_NODEIDTYPE_NUMERIC, {.numeric = 46u}},
      .nodeClass = (UA_NodeClass)32,
      .browseName = {0, {11, (UA_Byte*)"HasProperty"}},
      .displayName = (UA_LocalizedTextListEntry*)&n14_dn,
      .description = NULL,
      .writeMask = 0u,
      .referencesSize = 1,
      .references = (UA_NodeReferenceKind*)n14_refs,
      .context = NULL,
      .constructed = true
    },
    .isAbstract = false,
    .symmetric = false,
    .inverseName = {{0, NULL}, {10, (UA_Byte*)"PropertyOf"}},
    .referenceTypeIndex = 13u,
    .subTypes = {{8192u,0u,0u,0u,}}
  } },
  { .referenceTypeNode = {
    .head = {
      .nodeId = {0, UA_NODEIDTYPE_NUMERIC, {.numeric = 47u}},
      .nodeClass = (UA_NodeClass)32,
      .browseName = {0, {12, (UA_Byte*)"HasComponent"}},
      .displayName = (UA_LocalizedTextListEntry*)&n15_dn,
      .description = NULL,
      .writeMask = 0u,
      .referencesSize = 2,
      .references = (UA_NodeReferenceKind*)n15_refs,
      .context = NULL,
      .constructed = true
    },
    .isAbstract = false,
    .symmetric = false,
    .inverseName = {{0, NULL}, {11, (UA_Byte*)"ComponentOf"}},
    .referenceTypeIndex = 14u,
    .subTypes = {{81920u,0u,0u,0u,}}
  } },
  { .referenceTypeNode = {
    .head = {
      .nodeId = {0, UA_NODEIDTYPE_NUMERIC, {.numeric = 48u}},
      .nodeClass = (UA_NodeClass)32,
      .browseName = {0, {11, (UA_Byte*)"HasNotifier"}},
      .displayName = (UA_LocalizedTextListEntry*)&n16_dn,
      .description = NULL,
      .writeMask = 0u,
      .referencesSize = 1,
      .references = (UA_NodeReferenceKind*)n16_refs,
      .context = NULL,
      .constructed = true
    },
    .isAbstract = false,
    .symmetric = false,
    .inverseName = {{0, NULL}, {10, (UA_Byte*)"NotifierOf"}},
    .referenceTypeIndex = 15u,
    .subTypes = {{32768u,0u,0u,0u,}}
  } },
  { .referenceTypeNode = {
    .head = {
      .nodeId = {0, UA_NODEIDTYPE_NUMERIC, {.numeric = 49u}},
      .nodeClass = (UA_NodeClass)32,
      .browseName = {0, {19, (UA_Byte*)"HasOrderedComponent"}},
      .displayName = (UA_LocalizedTextListEntry*)&n17_dn,
      .description = NULL,
      .writeMask = 0u,
      .referencesSize = 1,
      .references = (UA_NodeReferenceKind*)n17_refs,
      .context = NULL,
      .constructed = true
    },
    .isAbstract = false,
    .symmetric = false,
    .inverseName = {{0, NULL}, {18, (UA_Byte*)"OrderedComponentOf"}},
    .referenceTypeIndex = 16u,
    .subTypes = {{65536u,0u,0u,0u,}}
  } },
  { .objectTypeNode = {
    .head = {
      .nodeId = {0, UA_NODEIDTYPE_NUMERIC, {.numeric = 58u}},
      .nodeClass = (UA_NodeClass)8,
      .browseName = {0, {14, (UA_Byte*)"BaseObjectType"}},
      .displayName = (UA_LocalizedTextListEntry*)&n18_dn,
      .description = NULL,
      .writeMask = 0u,
      .referencesSize = 3,
      .references = (UA_NodeReferenceKind*)n18_refs,
      .context = NULL,
      .constructed = true
    },
    .isAbstract = false
  } },
  { .objectTypeNode = {
    .head = {
      .nodeId = {0, UA_NODEIDTYPE_NUMERIC, {.numeric = 61u}},
      .nodeClass = (UA_NodeClass)8,
      .browseName = {0, {10, (UA_Byte*)"FolderType"}},
      .displayName = (UA_LocalizedTextListEntry*)&n19_dn,
      .description = NULL,
      .writeMask = 0u,
      .referencesSize = 2,
      .references = (UA_NodeReferenceKind*)n19_refs,
      .context = NULL,
      .constructed = true
    },
    .isAbstract = false
  } },
  { .variableTypeNode = {
    .head = {
      .nodeId = {0, UA_NODEIDTYPE_NUMERIC, {.numeric = 62u}},
      .nodeClass = (UA_NodeClass)16,
      .browseName = {0, {16, (UA_Byte*)"BaseVariableType"}},
      .displayName = (UA_LocalizedTextListEntry*)&n20_dn,
      .description = NULL,
      .writeMask = 0u,
      .referencesSize = 2,
      .references = (UA_NodeReferenceKind*)n20_refs,
      .context = NULL,
      .constructed = true
    },
    .dataType = {0, UA_NODEIDTYPE_NUMERIC, {.numeric = 24u}},
    .valueRank = -2,
    .arrayDimensionsSize = 0,
    .arrayDimensions = NULL,
    .valueSourceType = UA_VALUESOURCETYPE_INTERNAL,
    .valueSource = {.internal = {{0}, {0}}},
    .isAbstract = true
  } },
  { .variableTypeNode = {
    .head = {
      .nodeId = {0, UA_NODEIDTYPE_NUMERIC, {.numeric = 63u}},
      .nodeClass = (UA_NodeClass)16,
      .browseName = {0, {20, (UA_Byte*)"BaseDataVariableType"}},
      .displayName = (UA_LocalizedTextListEntry*)&n21_dn,
      .description = NULL,
      .writeMask = 0u,
      .referencesSize = 2,
      .references = (UA_NodeReferenceKind*)n21_refs,
      .context = NULL,
      .constructed = true
    },
    .dataType = {0, UA_NODEIDTYPE_NUMERIC, {.numeric = 24u}},
    .valueRank = -2,
    .arrayDimensionsSize = 0,
    .arrayDimensions = NULL,
    .valueSourceType = UA_VALUESOURCETYPE_INTERNAL,
    .valueSource = {.internal = {{0}, {0}}},
    .isAbstract = false
  } },
  { .variableTypeNode = {
    .head = {
      .nodeId = {0, UA_NODEIDTYPE_NUMERIC, {.numeric = 68u}},
      .nodeClass = (UA_NodeClass)16,
      .browseName = {0, {12, (UA_Byte*)"PropertyType"}},
      .displayName = (UA_LocalizedTextListEntry*)&n22_dn,
      .description = NULL,
      .writeMask = 0u,
      .referencesSize = 1,
      .references = (UA_NodeReferenceKind*)n22_refs,
      .context = NULL,
      .constructed = true
    },
    .dataType = {0, UA_NODEIDTYPE_NUMERIC, {.numeric = 24u}},
    .valueRank = -2,
    .arrayDimensionsSize = 0,
    .arrayDimensions = NULL,
    .valueSourceType = UA_VALUESOURCETYPE_INTERNAL,
    .valueSource = {.internal = {{0}, {0}}},
    .isAbstract = false
  } },
  { .objectNode = {
    .head = {
      .nodeId = {0, UA_NODEIDTYPE_NUMERIC, {.numeric = 84u}},
      .nodeClass = (UA_NodeClass)1,
      .browseName = {0, {4, (UA_Byte*)"Root"}},
      .displayName = (UA_LocalizedTextListEntry*)&n23_dn,
      .description = NULL,
      .writeMask = 0u,
      .referencesSize = 2,
      .references = (UA_NodeReferenceKind*)n23_refs,
      .context = NULL,
      .constructed = true
    },
    .eventNotifier = 0u
  } },
  { .objectNode = {
    .head = {
      .nodeId = {0, UA_NODEIDTYPE_NUMERIC, {.numeric = 85u}},
      .nodeClass = (UA_NodeClass)1,
      .browseName = {0, {7, (UA_Byte*)"Objects"}},
      .displayName = (UA_LocalizedTextListEntry*)&n24_dn,
      .description = NULL,
      .writeMask = 0u,
      .referencesSize = 3,
      .references = (UA_NodeReferenceKind*)n24_refs,
      .context = NULL,
      .constructed = true
    },
    .eventNotifier = 0u
  } },
  { .objectNode = {
    .head = {
      .nodeId = {0, UA_NODEIDTYPE_NUMERIC, {.numeric = 86u}},
      .nodeClass = (UA_NodeClass)1,
      .browseName = {0, {5, (UA_Byte*)"Types"}},
      .displayName = (UA_LocalizedTextListEntry*)&n25_dn,
      .description = NULL,
      .writeMask = 0u,
      .referencesSize = 3,
      .references = (UA_NodeReferenceKind*)n25_refs,
      .context = NULL,
      .constructed = true
    },
    .eventNotifier = 0u
  } },
  { .objectNode = {
    .head = {
      .nodeId = {0, UA_NODEIDTYPE_NUMERIC, {.numeric = 87u}},
      .nodeClass = (UA_NodeClass)1,
      .browseName = {0, {5, (UA_Byte*)"Views"}},
      .displayName = (UA_LocalizedTextListEntry*)&n26_dn,
      .description = NULL,
      .writeMask = 0u,
      .referencesSize = 2,
      .references = (UA_NodeReferenceKind*)n26_refs,
      .context = NULL,
      .constructed = true
    },
    .eventNotifier = 0u
  } },
  { .objectNode = {
    .head = {
      .nodeId = {0, UA_NODEIDTYPE_NUMERIC, {.numeric = 88u}},
      .nodeClass = (UA_NodeClass)1,
      .browseName = {0, {11, (UA_Byte*)"ObjectTypes"}},
      .displayName = (UA_LocalizedTextListEntry*)&n27_dn,
      .description = NULL,
      .writeMask = 0u,
      .referencesSize = 3,
      .references = (UA_NodeReferenceKind*)n27_refs,
      .context = NULL,
      .constructed = true
    },
    .eventNotifier = 0u
  } },
  { .objectNode = {
    .head = {
      .nodeId = {0, UA_NODEIDTYPE_NUMERIC, {.numeric = 89u}},
      .nodeClass = (UA_NodeClass)1,
      .browseName = {0, {13, (UA_Byte*)"VariableTypes"}},
      .displayName = (UA_LocalizedTextListEntry*)&n28_dn,
      .description = NULL,
      .writeMask = 0u,
      .referencesSize = 3,
      .references = (UA_NodeReferenceKind*)n28_refs,
      .context = NULL,
      .constructed = true
    },
    .eventNotifier = 0u
  } },
  { .objectNode = {
    .head = {
      .nodeId = {0, UA_NODEIDTYPE_NUMERIC, {.numeric = 90u}},
      .nodeClass = (UA_NodeClass)1,
      .browseName = {0, {9, (UA_Byte*)"DataTypes"}},
      .displayName = (UA_LocalizedTextListEntry*)&n29_dn,
      .description = NULL,
      .writeMask = 0u,
      .referencesSize = 3,
      .references = (UA_NodeReferenceKind*)n29_refs,
      .context = NULL,
      .constructed = true
    },
    .eventNotifier = 0u
  } },
  { .objectNode = {
    .head = {
      .nodeId = {0, UA_NODEIDTYPE_NUMERIC, {.numeric = 91u}},
      .nodeClass = (UA_NodeClass)1,
      .browseName = {0, {14, (UA_Byte*)"ReferenceTypes"}},
      .displayName = (UA_LocalizedTextListEntry*)&n30_dn,
      .description = NULL,
      .writeMask = 0u,
      .referencesSize = 3,
      .references = (UA_NodeReferenceKind*)n30_refs,
      .context = NULL,
      .constructed = true
    },
    .eventNotifier = 0u
  } },
  { .objectTypeNode = {
    .head = {
      .nodeId = {0, UA_NODEIDTYPE_NUMERIC, {.numeric = 2041u}},
      .nodeClass = (UA_NodeClass)8,
      .browseName = {0, {13, (UA_Byte*)"BaseEventType"}},
      .displayName = (UA_LocalizedTextListEntry*)&n31_dn,
      .description = NULL,
      .writeMask = 0u,
      .referencesSize = 2,
      .references = (UA_NodeReferenceKind*)n31_refs,
      .context = NULL,
      .constructed = true
    },
    .isAbstract = false
  } },
  { .objectNode = {
    .head = {
      .nodeId = {0, UA_NODEIDTYPE_NUMERIC, {.numeric = 2253u}},
      .nodeClass = (UA_NodeClass)1,
      .browseName = {0, {6, (UA_Byte*)"Server"}},
      .displayName = (UA_LocalizedTextListEntry*)&n32_dn,
      .description = NULL,
      .writeMask = 0u,
      .referencesSize = 4,
      .references = (UA_NodeReferenceKind*)n32_refs,
      .context = NULL,
      .constructed = true
    },
    .eventNotifier = 0u
  } },
  { .variableNode = {
    .head = {
      .nodeId = {0, UA_NODEIDTYPE_NUMERIC, {.numeric = 2254u}},
      .nodeClass = (UA_NodeClass)2,
      .browseName = {0, {11, (UA_Byte*)"ServerArray"}},
      .displayName = (UA_LocalizedTextListEntry*)&n33_dn,
      .description = NULL,
      .writeMask = 0u,
      .referencesSize = 2,
      .references = (UA_NodeReferenceKind*)n33_refs,
      .context = NULL,
      .constructed = true
    },
    .dataType = {0, UA_NODEIDTYPE_NUMERIC, {.numeric = 24u}},
    .valueRank = 1,
    .arrayDimensionsSize = 0,
    .arrayDimensions = NULL,
    .valueSourceType = UA_VALUESOURCETYPE_INTERNAL,
    .valueSource = {.internal = {{0}, {0}}},
    .accessLevel = 1u,
    .minimumSamplingInterval = 0.000000,
    .historizing = false,
    .isDynamic = false
  } },
  { .variableNode = {
    .head = {
      .nodeId = {0, UA_NODEIDTYPE_NUMERIC, {.numeric = 2255u}},
      .nodeClass = (UA_NodeClass)2,
      .browseName = {0, {14, (UA_Byte*)"NamespaceArray"}},
      .displayName = (UA_LocalizedTextListEntry*)&n34_dn,
      .description = NULL,
      .writeMask = 0u,
      .referencesSize = 2,
      .references = (UA_NodeReferenceKind*)n34_refs,
      .context = NULL,
      .constructed = true
    },
    .dataType = {0, UA_NODEIDTYPE_NUMERIC, {.numeric = 24u}},
    .valueRank = 1,
    .arrayDimensionsSize = 0,
    .arrayDimensions = NULL,
    .valueSourceType = UA_VALUESOURCETYPE_INTERNAL,
    .valueSource = {.internal = {{0}, {0}}},
    .accessLevel = 1u,
    .minimumSamplingInterval = 0.000000,
    .historizing = false,
    .isDynamic = false
  } },
  { .variableNode = {
    .head = {
      .nodeId = {0, UA_NODEIDTYPE_NUMERIC, {.numeric = 2256u}},
      .nodeClass = (UA_NodeClass)2,
      .browseName = {0, {12, (UA_Byte*)"ServerStatus"}},
      .displayName = (UA_LocalizedTextListEntry*)&n35_dn,
      .description = NULL,
      .writeMask = 0u,
      .referencesSize = 3,
      .references = (UA_NodeReferenceKind*)n35_refs,
      .context = NULL,
      .constructed = true
    },
    .dataType = {0, UA_NODEIDTYPE_NUMERIC, {.numeric = 24u}},
    .valueRank = -1,
    .arrayDimensionsSize = 0,
    .arrayDimensions = NULL,
    .valueSourceType = UA_VALUESOURCETYPE_INTERNAL,
    .valueSource = {.internal = {{0}, {0}}},
    .accessLevel = 1u,
    .minimumSamplingInterval = 0.000000,
    .historizing = false,
    .isDynamic = false
  } },
  { .variableNode = {
    .head = {
      .nodeId = {0, UA_NODEIDTYPE_NUMERIC, {.numeric = 2257u}},
      .nodeClass = (UA_NodeClass)2,
      .browseName = {0, {9, (UA_Byte*)"StartTime"}},
      .displayName = (UA_LocalizedTextListEntry*)&n36_dn,
      .description = NULL,
      .writeMask = 0u,
      .referencesSize = 2,
      .references = (UA_NodeReferenceKind*)n36_refs,
      .context = NULL,
      .constructed = true
    },
    .dataType = {0, UA_NODEIDTYPE_NUMERIC, {.numeric = 24u}},
    .valueRank = -1,
    .arrayDimensionsSize = 0,
    .arrayDimensions = NULL,
    .valueSourceType = UA_VALUESOURCETYPE_INTERNAL,
    .valueSource = {.internal = {{0}, {0}}},
    .accessLevel = 1u,
    .minimumSamplingInterval = 0.000000,
    .historizing = false,
    .isDynamic = false
  } },
  { .variableNode = {
    .head = {
      .nodeId = {0, UA_NODEIDTYPE_NUMERIC, {.numeric = 2258u}},
      .nodeClass = (UA_NodeClass)2,
      .browseName = {0, {11, (UA_Byte*)"CurrentTime"}},
      .displayName = (UA_LocalizedTextListEntry*)&n37_dn,
      .description = NULL,
      .writeMask = 0u,
      .referencesSize = 2,
      .references = (UA_NodeReferenceKind*)n37_refs,
      .context = NULL,
      .constructed = true
    },
    .dataType = {0, UA_NODEIDTYPE_NUMERIC, {.numeric = 24u}},
    .valueRank = -1,
    .arrayDimensionsSize = 0,
    .arrayDimensions = NULL,
    .valueSourceType = UA_VALUESOURCETYPE_INTERNAL,
    .valueSource = {.internal = {{0}, {0}}},
    .accessLevel = 1u,
    .minimumSamplingInterval = 100.000000,
    .historizing = false,
    .isDynamic = false
  } },
  { .variableNode = {
    .head = {
      .nodeId = {0, UA_NODEIDTYPE_NUMERIC, {.numeric = 2259u}},
      .nodeClass = (UA_NodeClass)2,
      .browseName = {0, {5, (UA_Byte*)"State"}},
      .displayName = (UA_LocalizedTextListEntry*)&n38_dn,
      .description = NULL,
      .writeMask = 0u,
      .referencesSize = 2,
      .references = (UA_NodeReferenceKind*)n38_refs,
      .context = NULL,
      .constructed = true
    },
    .dataType = {0, UA_NODEIDTYPE_NUMERIC, {.numeric = 24u}},
    .valueRank = -1,
    .arrayDimensionsSize = 0,
    .arrayDimensions = NULL,
    .valueSourceType = UA_VALUESOURCETYPE_INTERNAL,
    .valueSource = {.internal = {{0}, {0}}},
    .accessLevel = 1u,
    .minimumSamplingInterval = 0.000000,
    .historizing = false,
    .isDynamic = false
  } },
  { .variableNode = {
    .head = {
      .nodeId = {0, UA_NODEIDTYPE_NUMERIC, {.numeric = 2260u}},
      .nodeClass = (UA_NodeClass)2,
      .browseName = {0, {9, (UA_Byte*)"BuildInfo"}},
      .displayName = (UA_LocalizedTextListEntry*)&n39_dn,
      .description = NULL,
      .writeMask = 0u,
      .referencesSize = 3,
      .references = (UA_NodeReferenceKind*)n39_refs,
      .context = NULL,
      .constructed = true
    },
    .dataType = {0, UA_NODEIDTYPE_NUMERIC, {.numeric = 24u}},
    .valueRank = -1,
    .arrayDimensionsSize = 0,
    .arrayDimensions = NULL,
    .valueSourceType = UA_VALUESOURCETYPE_INTERNAL,
    .valueSource = {.internal = {{0}, {0}}},
    .accessLevel = 1u,
    .minimumSamplingInterval = 0.000000,
    .historizing = false,
    .isDynamic = false
  } },
  { .variableNode = {
    .head = {
      .nodeId = {0, UA_NODEIDTYPE_NUMERIC, {.numeric = 2261u}},
      .nodeClass = (UA_NodeClass)2,
      .browseName = {0, {11, (UA_Byte*)"ProductName"}},
      .displayName = (UA_LocalizedTextListEntry*)&n40_dn,
      .description = NULL,
      .writeMask = 0u,
      .referencesSize = 2,
      .references = (UA_NodeReferenceKind*)n40_refs,
      .context = NULL,
      .constructed = true
    },
    .dataType = {0, UA_NODEIDTYPE_NUMERIC, {.numeric = 24u}},
    .valueRank = -1,
    .arrayDimensionsSize = 0,
    .arrayDimensions = NULL,
    .valueSourceType = UA_VALUESOURCETYPE_INTERNAL,
    .valueSource = {.internal = {{0}, {0}}},
    .accessLevel = 1u,
    .minimumSamplingInterval = 0.000000,
    .historizing = false,
    .isDynamic = false
  } },
  { .variableNode = {
    .head = {
      .nodeId = {0, UA_NODEIDTYPE_NUMERIC, {.numeric = 2262u}},
      .nodeClass = (UA_NodeClass)2,
      .browseName = {0, {10, (UA_Byte*)"ProductUri"}},
      .displayName = (UA_LocalizedTextListEntry*)&n41_dn,
      .description = NULL,
      .writeMask = 0u,
      .referencesSize = 2,
      .references = (UA_NodeReferenceKind*)n41_refs,
      .context = NULL,
      .constructed = true
    },
    .dataType = {0, UA_NODEIDTYPE_NUMERIC, {.numeric = 24u}},
    .valueRank = -1,
    .arrayDimensionsSize = 0,
    .arrayDimensions = NULL,
    .valueSourceType = UA_VALUESOURCETYPE_INTERNAL,
    .valueSource = {.internal = {{0}, {0}}},
    .accessLevel = 1u,
    .minimumSamplingInterval = 0.000000,
    .historizing = false,
    .isDynamic = false
  } },
  { .variableNode = {
    .head = {
      .nodeId = {0, UA_NODEIDTYPE_NUMERIC, {.numeric = 2263u}},
      .nodeClass = (UA_NodeClass)2,
      .browseName = {0, {16, (UA_Byte*)"ManufacturerName"}},
      .displayName = (UA_LocalizedTextListEntry*)&n42_dn,
      .description = NULL,
      .writeMask = 0u,
      .referencesSize = 2,
      .references = (UA_NodeReferenceKind*)n42_refs,
      .context = NULL,
      .constructed = true
    },
    .dataType = {0, UA_NODEIDTYPE_NUMERIC, {.numeric = 24u}},
    .valueRank = -1,
    .arrayDimensionsSize = 0,
    .arrayDimensions = NULL,
    .valueSourceType = UA_VALUESOURCETYPE_INTERNAL,
    .valueSource = {.internal = {{0}, {0}}},
    .accessLevel = 1u,
    .minimumSamplingInterval = 0.000000,
    .historizing = false,
    .isDynamic = false
  } },
  { .variableNode = {
    .head = {
      .nodeId = {0, UA_NODEIDTYPE_NUMERIC, {.numeric = 2264u}},
      .nodeClass = (UA_NodeClass)2,
      .browseName = {0, {15, (UA_Byte*)"SoftwareVersion"}},
      .displayName = (UA_LocalizedTextListEntry*)&n43_dn,
      .description = NULL,
      .writeMask = 0u,
      .referencesSize = 2,
      .references = (UA_NodeReferenceKind*)n43_refs,
      .context = NULL,
      .constructed = true
    },
    .dataType = {0, UA_NODEIDTYPE_NUMERIC, {.numeric = 24u}},
    .valueRank = -1,
    .arrayDimensionsSize = 0,
    .arrayDimensions = NULL,
    .valueSourceType = UA_VALUESOURCETYPE_INTERNAL,
    .valueSource = {.internal = {{0}, {0}}},
    .accessLevel = 1u,
    .minimumSamplingInterval = 0.000000,
    .historizing = false,
    .isDynamic = false
  } },
  { .variableNode = {
    .head = {
      .nodeId = {0, UA_NODEIDTYPE_NUMERIC, {.numeric = 2265u}},
      .nodeClass = (UA_NodeClass)2,
      .browseName = {0, {11, (UA_Byte*)"BuildNumber"}},
      .displayName = (UA_LocalizedTextListEntry*)&n44_dn,
      .description = NULL,
      .writeMask = 0u,
      .referencesSize = 2,
      .references = (UA_NodeReferenceKind*)n44_refs,
      .context = NULL,
      .constructed = true
    },
    .dataType = {0, UA_NODEIDTYPE_NUMERIC, {.numeric = 24u}},
    .valueRank = -1,
    .arrayDimensionsSize = 0,
    .arrayDimensions = NULL,
    .valueSourceType = UA_VALUESOURCETYPE_INTERNAL,
    .valueSource = {.internal = {{0}, {0}}},
    .accessLevel = 1u,
    .minimumSamplingInterval = 0.000000,
    .historizing = false,
    .isDynamic = false
  } },
  { .variableNode = {
    .head = {
      .nodeId = {0, UA_NODEIDTYPE_NUMERIC, {.numeric = 2266u}},
      .nodeClass = (UA_NodeClass)2,
      .browseName = {0, {9, (UA_Byte*)"BuildDate"}},
      .displayName = (UA_LocalizedTextListEntry*)&n45_dn,
      .description = NULL,
      .writeMask = 0u,
      .referencesSize = 2,
      .references = (UA_NodeReferenceKind*)n45_refs,
      .context = NULL,
      .constructed = true
    },
    .dataType = {0, UA_NODEIDTYPE_NUMERIC, {.numeric = 24u}},
    .valueRank = -1,
    .arrayDimensionsSize = 0,
    .arrayDimensions = NULL,
    .valueSourceType = UA_VALUESOURCETYPE_INTERNAL,
    .valueSource = {.internal = {{0}, {0}}},
    .accessLevel = 1u,
    .minimumSamplingInterval = 0.000000,
    .historizing = false,
    .isDynamic = false
  } },
  { .objectNode = {
    .head = {
      .nodeId = {0, UA_NODEIDTYPE_NUMERIC, {.numeric = 3048u}},
      .nodeClass = (UA_NodeClass)1,
      .browseName = {0, {10, (UA_Byte*)"EventTypes"}},
      .displayName = (UA_LocalizedTextListEntry*)&n46_dn,
      .description = NULL,
      .writeMask = 0u,
      .referencesSize = 3,
      .references = (UA_NodeReferenceKind*)n46_refs,
      .context = NULL,
      .constructed = true
    },
    .eventNotifier = 0u
  } },
  { .referenceTypeNode = {
    .head = {
      .nodeId = {0, UA_NODEIDTYPE_NUMERIC, {.numeric = 17603u}},
      .nodeClass = (UA_NodeClass)32,
      .browseName = {0, {12, (UA_Byte*)"HasInterface"}},
      .displayName = (UA_LocalizedTextListEntry*)&n47_dn,
      .description = NULL,
      .writeMask = 0u,
      .referencesSize = 1,
      .references = (UA_NodeReferenceKind*)n47_refs,
      .context = NULL,
      .constructed = true
    },
    .isAbstract = false,
    .symmetric = false,
    .inverseName = {{0, NULL}, {11, (UA_Byte*)"InterfaceOf"}},
    .referenceTypeIndex = 17u,
    .subTypes = {{131072u,0u,0u,0u,}}
  } },
};

const size_t ua_ns0_nodes_count = 48;
