/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/.
 *
 *    Copyright 2026 (c) Autonomy Logic
 */

/*
 * gen-ns0 -- emit a const, flash-resident namespace zero.
 *
 * A server's namespace zero is identical on every device and every boot, and
 * it is never modified at runtime with node management compiled out. Building
 * it into the heap at startup therefore costs 18,992 bytes of RAM on a
 * Cortex-M4 to hold about 1.2 KB of content. Emitted as const it is 13,641
 * bytes of flash and no RAM at all.
 *
 * The table is read off a REAL MINIMAL server after run_startup, not inferred
 * from the nodeset XML, so it is by construction what this version of
 * open62541 actually builds. Regenerate after an upstream bump.
 *
 * Build (from the repo root, against a host build of the library):
 *
 *   cmake -S . -B build-host -DUA_NAMESPACE_ZERO=MINIMAL ...
 *   cmake --build build-host --target open62541
 *   cc -std=c99 -Iinclude -Ibuild-host/src_generated -Iplugins/include \
 *      -Iarch -Ideps tools/arduino/gen-ns0.c build-host/bin/libopen62541.a \
 *      -o gen-ns0
 *   ./gen-ns0 arch/arduino/ua_ns0_flash.c
 *
 * The output is committed rather than generated at library-build time: it is
 * deterministic, it changes only when upstream does, and generating it would
 * mean every library build also doing a host build of open62541.
 */
#include <open62541/server.h>
#include <open62541/server_config_default.h>
#include <open62541/plugin/nodestore.h>
#include <stdio.h>
#include <string.h>
#include <stdlib.h>

#define MAXN 256
static const UA_Node *nodes[MAXN];
static int n_nodes = 0;
static void collect(void *ctx, const UA_Node *n) { (void)ctx; if (n_nodes < MAXN) nodes[n_nodes++] = n; }

static int by_id(const void *a, const void *b) {
    const UA_NodeHead *x = &(*(const UA_Node **)a)->head, *y = &(*(const UA_Node **)b)->head;
    if (x->nodeId.namespaceIndex != y->nodeId.namespaceIndex)
        return x->nodeId.namespaceIndex < y->nodeId.namespaceIndex ? -1 : 1;
    if (x->nodeId.identifier.numeric == y->nodeId.identifier.numeric) return 0;
    return x->nodeId.identifier.numeric < y->nodeId.identifier.numeric ? -1 : 1;
}

static void emit_str(FILE *f, const UA_String *s) {
    if (s->length == 0) { fprintf(f, "{0, NULL}"); return; }
    fprintf(f, "{%zu, (UA_Byte*)\"", s->length);
    for (size_t i = 0; i < s->length; i++) {
        unsigned char c = s->data[i];
        if (c == '"' || c == '\\') fprintf(f, "\\%c", c);
        else if (c >= 32 && c < 127) fputc(c, f);
        else fprintf(f, "\\x%02x", c);
    }
    fprintf(f, "\"}");
}
static void emit_lt(FILE *f, const UA_LocalizedText *lt) {
    fprintf(f, "{"); emit_str(f, &lt->locale); fprintf(f, ", "); emit_str(f, &lt->text); fprintf(f, "}");
}
static void emit_nodeid(FILE *f, const UA_NodeId *id) {
    if (id->identifierType != UA_NODEIDTYPE_NUMERIC) { fprintf(stderr, "non-numeric nodeid\n"); exit(4); }
    fprintf(f, "{%u, UA_NODEIDTYPE_NUMERIC, {.numeric = %uu}}", id->namespaceIndex, id->identifier.numeric);
}
static const char *class_member(UA_NodeClass c) {
    switch (c) {
        case UA_NODECLASS_OBJECT:        return "objectNode";
        case UA_NODECLASS_VARIABLE:      return "variableNode";
        case UA_NODECLASS_OBJECTTYPE:    return "objectTypeNode";
        case UA_NODECLASS_VARIABLETYPE:  return "variableTypeNode";
        case UA_NODECLASS_REFERENCETYPE: return "referenceTypeNode";
        case UA_NODECLASS_DATATYPE:      return "dataTypeNode";
        default: return NULL;
    }
}

int main(int argc, char **argv) {
    if (argc < 2) { fprintf(stderr, "usage: gen-ns0 <out.c>\n"); return 1; }
    UA_Server *s = UA_Server_new();
    UA_ServerConfig *c = UA_Server_getConfig(s);
    UA_ServerConfig_setMinimal(c, 47842, NULL);
    if (UA_Server_run_startup(s) != UA_STATUSCODE_GOOD) { fprintf(stderr, "startup failed\n"); return 1; }
    c->nodestore->iterate(c->nodestore, collect, NULL);
    qsort(nodes, n_nodes, sizeof(nodes[0]), by_id);

    /* open62541 logs to stdout, so the generated source must go to a file of
     * its own or the log lines land in the middle of it. */
    FILE *f = fopen(argv[1], "w");
    if (!f) { perror("open"); return 1; }
    fprintf(f, "/* GENERATED by tools/arduino/gen-ns0.c -- do not edit.\n"
               " *\n"
               " * A const, flash-resident namespace zero: %d nodes, read off a real\n"
               " * MINIMAL server after run_startup rather than inferred from the nodeset.\n"
               " */\n\n#include \"ua_ns0_flash.h\"\n\n", n_nodes);

    for (int i = 0; i < n_nodes; i++) {
        const UA_NodeHead *h = &nodes[i]->head;
        for (size_t k = 0; k < h->referencesSize; k++) {
            const UA_NodeReferenceKind *rk = &h->references[k];
            if (rk->hasRefTree) { fprintf(stderr, "node %u uses a ref TREE\n", h->nodeId.identifier.numeric); return 2; }
            fprintf(f, "static const UA_ReferenceTarget n%d_k%zu[] = {", i, k);
            for (size_t t = 0; t < rk->targetsSize; t++) {
                UA_NodeId tid = UA_NodePointer_toNodeId(rk->targets.array[t].targetId);
                if (tid.identifierType != UA_NODEIDTYPE_NUMERIC ||
                    tid.namespaceIndex >= 64 || tid.identifier.numeric >= (1u<<24)) {
                    fprintf(stderr, "target not immediate-encodable\n"); return 5;
                }
                fprintf(f, "\n  {UA_NS0_NP(%u, %uu), %uu},",
                        tid.namespaceIndex, tid.identifier.numeric,
                        rk->targets.array[t].targetNameHash);
            }
            fprintf(f, "\n};\n");
        }
        if (h->referencesSize) {
            fprintf(f, "static const UA_NodeReferenceKind n%d_refs[] = {", i);
            for (size_t k = 0; k < h->referencesSize; k++) {
                const UA_NodeReferenceKind *rk = &h->references[k];
                fprintf(f, "\n  {{(UA_ReferenceTarget*)n%d_k%zu}, %zu, false, %u, %s},",
                        i, k, rk->targetsSize, rk->referenceTypeIndex, rk->isInverse ? "true" : "false");
            }
            fprintf(f, "\n};\n");
        }
        if (h->displayName) {
            fprintf(f, "static const UA_LocalizedTextListEntry n%d_dn = {NULL, ", i);
            emit_lt(f, &h->displayName->localizedText); fprintf(f, "};\n");
        }
    }
    fprintf(f, "\n");

    fprintf(f, "const UA_Node ua_ns0_nodes[%d] = {\n", n_nodes);
    for (int i = 0; i < n_nodes; i++) {
        const UA_NodeHead *h = &nodes[i]->head;
        const char *mem = class_member(h->nodeClass);
        if (!mem) { fprintf(stderr, "unhandled class %d\n", (int)h->nodeClass); return 3; }
        fprintf(f, "  { .%s = {\n    .head = {\n      .nodeId = ", mem);
        emit_nodeid(f, &h->nodeId);
        fprintf(f, ",\n      .nodeClass = (UA_NodeClass)%d,\n      .browseName = {%u, ",
                (int)h->nodeClass, h->browseName.namespaceIndex);
        emit_str(f, &h->browseName.name);
        fprintf(f, "},\n      .displayName = ");
        if (h->displayName) fprintf(f, "(UA_LocalizedTextListEntry*)&n%d_dn", i); else fprintf(f, "NULL");
        fprintf(f, ",\n      .description = NULL,\n      .writeMask = %uu,\n      .referencesSize = %zu,\n      .references = ",
                h->writeMask, h->referencesSize);
        if (h->referencesSize) fprintf(f, "(UA_NodeReferenceKind*)n%d_refs", i); else fprintf(f, "NULL");
        fprintf(f, ",\n      .context = NULL,\n      .constructed = true\n    },\n");

        switch (h->nodeClass) {
        case UA_NODECLASS_OBJECT:
            fprintf(f, "    .eventNotifier = %uu\n", nodes[i]->objectNode.eventNotifier); break;
        case UA_NODECLASS_OBJECTTYPE:
            fprintf(f, "    .isAbstract = %s\n", nodes[i]->objectTypeNode.isAbstract ? "true":"false"); break;
        case UA_NODECLASS_DATATYPE:
            fprintf(f, "    .isAbstract = %s\n", nodes[i]->dataTypeNode.isAbstract ? "true":"false"); break;
        case UA_NODECLASS_REFERENCETYPE: {
            const UA_ReferenceTypeNode *r = &nodes[i]->referenceTypeNode;
            fprintf(f, "    .isAbstract = %s,\n    .symmetric = %s,\n    .inverseName = ",
                    r->isAbstract?"true":"false", r->symmetric?"true":"false");
            emit_lt(f, &r->inverseName);
            fprintf(f, ",\n    .referenceTypeIndex = %uu,\n    .subTypes = {{", r->referenceTypeIndex);
            for (size_t b = 0; b < (sizeof(r->subTypes.bits)/sizeof(r->subTypes.bits[0])); b++)
                fprintf(f, "%uu,", r->subTypes.bits[b]);
            fprintf(f, "}}\n");
            break; }
        case UA_NODECLASS_VARIABLE: {
            const UA_VariableNode *v = &nodes[i]->variableNode;
            fprintf(f, "    .dataType = "); emit_nodeid(f, &v->dataType);
            fprintf(f, ",\n    .valueRank = %d,\n    .arrayDimensionsSize = 0,\n    .arrayDimensions = NULL,\n",
                    v->valueRank);
            fprintf(f, "    .valueSourceType = UA_VALUESOURCETYPE_INTERNAL,\n"
                       "    .valueSource = {.internal = {{0}, {0}}},\n");
            fprintf(f, "    .accessLevel = %uu,\n    .minimumSamplingInterval = %f,\n"
                       "    .historizing = %s,\n    .isDynamic = %s\n",
                    v->accessLevel, v->minimumSamplingInterval,
                    v->historizing?"true":"false", v->isDynamic?"true":"false");
            break; }
        case UA_NODECLASS_VARIABLETYPE: {
            const UA_VariableTypeNode *v = &nodes[i]->variableTypeNode;
            fprintf(f, "    .dataType = "); emit_nodeid(f, &v->dataType);
            fprintf(f, ",\n    .valueRank = %d,\n    .arrayDimensionsSize = 0,\n    .arrayDimensions = NULL,\n",
                    v->valueRank);
            fprintf(f, "    .valueSourceType = UA_VALUESOURCETYPE_INTERNAL,\n"
                       "    .valueSource = {.internal = {{0}, {0}}},\n");
            fprintf(f, "    .isAbstract = %s\n", v->isAbstract?"true":"false");
            break; }
        default: break;
        }
        fprintf(f, "  } },\n");
    }
    fprintf(f, "};\n\nconst size_t ua_ns0_nodes_count = %d;\n\n", n_nodes);

    /* referenceTypeIndex -> NodeId.
     *
     * Browse resolves reference types by a compact byte index, and the default
     * nodestore answers from its own tree. With namespace zero in flash there
     * is no tree to ask, so the mapping is emitted too. */
    {
        UA_NodeId byIndex[256];
        int maxIdx = -1;
        memset(byIndex, 0, sizeof(byIndex));
        for (int i = 0; i < n_nodes; i++) {
            if (nodes[i]->head.nodeClass != UA_NODECLASS_REFERENCETYPE) continue;
            UA_Byte ix = nodes[i]->referenceTypeNode.referenceTypeIndex;
            byIndex[ix] = nodes[i]->head.nodeId;
            if (ix > maxIdx) maxIdx = ix;
        }
        fprintf(f, "const UA_NodeId ua_ns0_reftype_ids[%d] = {\n", maxIdx + 1);
        for (int i = 0; i <= maxIdx; i++) {
            fprintf(f, "  ");
            if (byIndex[i].identifier.numeric == 0 && byIndex[i].namespaceIndex == 0)
                fprintf(f, "{0, UA_NODEIDTYPE_NUMERIC, {.numeric = 0u}}");
            else
                emit_nodeid(f, &byIndex[i]);
            fprintf(f, ",\n");
        }
        fprintf(f, "};\nconst size_t ua_ns0_reftype_count = %d;\n", maxIdx + 1);
    }
    fclose(f);
    UA_Server_delete(s);
    return 0;
}
